name: kubetrialdock
services:
  blog:
    build: ./docker/httpd
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '0.01'
          memory: 6M
        limits:
          cpus: '0.01'
          memory: 6M
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80

  load_balancer:
    image: nginxproxy/nginx-proxy
    ports:
      - 8949:80
    depends_on:
      - blog
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 6M
