services:
  blog-1:
#    image: blog  # Replace 'blog' with the actual image name for blog-1
    build: ./docker/httpd
    container_name: blog-1
#    networks:
#      - my_network
    ports:
       - 8051:80

  blog-2:
#    image: blog  # Replace 'blog' with the actual image name for blog-2
    build: ./docker/httpd
    container_name: blog-2
#    networks:
#      - my_network
    ports:
      - 8052:80

  blog-3:
     build: ./docker/httpd
     container_name: blog-3

  load_balancer:
#    image: lb  # Replace 'lb' with the actual image name for nginx_lb
    build: ./docker/nginx
    container_name: nginx_lb
    ports:
      - "8949:80"  # Exposes port 80 in the container on port 8949 on your host
    depends_on:
      - blog-1
      - blog-2
      - blog-3
    links:
      - blog-1
      - blog-2
      - blog-3
#    networks:
#      - my_network
    develop:
      watch:
         - action: sync+restart
           path: ./docker/nginx/default.conf
           target: /etc/nginx/conf.d/default.conf
    deploy:
      resources:
         reservtions:
            cpus: '0.05'
            memory: 6M
         limits:
            cpus: '0.05'
            memory: 6M
            pids: 10
      environment:
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=80


networks:
  my_network:
    driver: bridge
